CREATE TABLE veiculo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR2(10) NOT NULL UNIQUE,
    modelo VARCHAR2(100),
    cor VARCHAR2(50),
    data_cadastro TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE ticket (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veiculo_id NUMBER NOT NULL,
    vaga VARCHAR2(10) NOT NULL,
    entrada TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    saida TIMESTAMP NULL,
    valor NUMBER(10,2) NULL,
    status VARCHAR2(20) DEFAULT 'ABERTO' NOT NULL,
    CONSTRAINT fk_ticket_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculo(id)
);
CREATE INDEX ix_ticket_status ON ticket(status);
CREATE INDEX ix_ticket_entrada ON ticket(entrada);
CREATE UNIQUE INDEX uq_ticket_veiculo_aberto
  ON ticket (CASE WHEN status = 'ABERTO' THEN veiculo_id END);

COMMIT;